POST http://localhost:3000/auth/local/signup
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "user1_12345"
}

### success
POST http://localhost:3000/auth/local/signin
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlcjFAZ21haWwuY29tIiwiaWF0IjoxNzEwNzQ1NDQ0LCJleHAiOjE3MTA3NDYzNDR9.8zDrlpAG6XIJ1ljHe-t1CG7xT7vy4nMBVUAhAL_kvms

{
  "email": "user1@gmail.com",
  "password": "user1_12345"
}

### email error
POST http://localhost:3000/auth/local/signin
Content-Type: application/json

{
  "email": "user1@gmail.co",
  "password": "user1_12345"
}

### password error
POST http://localhost:3000/auth/local/signin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlcjFAZ21haWwuY29tIiwiaWF0IjoxNzEwNzQ1NDQ0LCJleHAiOjE3MTA3NDYzNDR9.8zDrlpAG6XIJ1ljHe-t1CG7xT7vy4nMBVUAhAL_kvms

{
  "email": "user1@gmail.com",
  "password": "user1_1234"
}

###
POST http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlcjFAZ21haWwuY29tIiwiaWF0IjoxNzEwNzQ2ODgwLCJleHAiOjE3MTA3NDc3ODB9.HAbHWKAtBtsDDpSxpGrD701cBOdvrfCEF8ljPs-gdRw

###
POST http://localhost:3000/auth/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlcjFAZ21haWwuY29tIiwiaWF0IjoxNzEwNzQ2OTQwLCJleHAiOjE3MTEzNTE3NDB9.PQBWE0vuH7n2HnIJNj6077JNoawoimwRdjZHRxRMSk4
